package manifest

import (
	"strings"
	"testing"
)

func TestMSBuildProjectExtraction(t *testing.T) {
	facts := ExtractMSBuild(file("src/Ordering.Api/Ordering.Api.csproj", `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Ordering.Api.Host</AssemblyName>
    <RootNamespace>Ordering.Api</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="MediatR">
      <Version>12.4.0</Version>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0" PrivateAssets="all" />
    <ProjectReference Include="..\Ordering.Domain\Ordering.Domain.csproj" />
  </ItemGroup>

</Project>
`))
	facts.Normalize()

	// RootNamespace is what a `using` in another project names, which makes it the more
	// useful of the two identities and the reason it wins over AssemblyName.
	if facts.Module.Name != "Ordering.Api" {
		t.Errorf("module name = %q, want RootNamespace to win", facts.Module.Name)
	}
	if facts.Module.LangVersion != "net8.0" {
		t.Errorf("target framework = %q", facts.Module.LangVersion)
	}
	if d := depOf(t, facts, "Serilog.AspNetCore", ScopeRuntime); d.Version != "8.0.1" {
		t.Errorf("attribute-spelled version = %q", d.Version)
	}
	// The child-element spelling of Version means the same thing, and both are generated by
	// different versions of the tooling — reading one would leave the other unversioned.
	if d := depOf(t, facts, "MediatR", ScopeRuntime); d.Version != "12.4.0" {
		t.Errorf("element-spelled version = %q", d.Version)
	}
	// `PrivateAssets="all"` says the package builds this project and is not propagated to
	// anything consuming it, which is a build dependency rather than a runtime one.
	depOf(t, facts, "StyleCop.Analyzers", ScopeBuild)

	// A ProjectReference is the only statement distinguishing a sibling project from a
	// nuget.org package, since `using Ordering.Domain` looks identical either way.
	d := depOf(t, facts, "Ordering.Domain", ScopeRuntime)
	if !d.Local || d.Source != "src/Ordering.Domain" {
		t.Errorf("project reference = %+v, want a local dep at src/Ordering.Domain", d)
	}

	// Exe is runnable. A class library is not, and listing one would put every library in
	// the set of things you can start.
	if len(facts.Entrypoints) != 1 || facts.Entrypoints[0].Name != "Ordering.Api" {
		t.Errorf("entrypoints = %+v", facts.Entrypoints)
	}
}

func TestMSBuildLibraryIsNotAnEntrypoint(t *testing.T) {
	facts := ExtractMSBuild(file("src/Ordering.Domain/Ordering.Domain.csproj", `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
</Project>
`))
	facts.Normalize()
	if len(facts.Entrypoints) != 0 {
		t.Errorf("entrypoints = %+v, want none for a library", facts.Entrypoints)
	}
	// The identity falls back to the filename, which is MSBuild's own rule for AssemblyName.
	if facts.Module.Name != "Ordering.Domain" {
		t.Errorf("name = %q, want the filename", facts.Module.Name)
	}
}

// Central Package Management puts every version a solution uses in one file, so a
// csproj-only reader would find a repository's whole supply chain declared nowhere.
func TestMSBuildCentralPackageManagement(t *testing.T) {
	facts := ExtractMSBuild(file("Directory.Packages.props", `<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Serilog" Version="4.0.0" />
    <PackageVersion Include="Npgsql" Version="8.0.3" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="9.32.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
`))
	facts.Normalize()
	if d := depOf(t, facts, "Serilog", ScopeRuntime); d.Version != "4.0.0" {
		t.Errorf("Serilog = %+v", d)
	}
	depOf(t, facts, "Npgsql", ScopeRuntime)
	depOf(t, facts, "SonarAnalyzer.CSharp", ScopeBuild)
}

// `Update` adjusts a package declared elsewhere, which is how Directory.Build.props sets a
// version without redeclaring the dependency. Both attributes name the same package.
func TestMSBuildUpdateNamesThePackage(t *testing.T) {
	facts := ExtractMSBuild(file("Directory.Build.props", `<Project>
  <ItemGroup>
    <PackageReference Update="Serilog" Version="4.0.1" />
  </ItemGroup>
</Project>
`))
	facts.Normalize()
	if d := depOf(t, facts, "Serilog", ScopeRuntime); d.Version != "4.0.1" {
		t.Errorf("Update-spelled dep = %+v", d)
	}
}

// Multi-targeting is one fact about a project, and the first framework alone would hide it.
func TestMSBuildKeepsEveryTargetFramework(t *testing.T) {
	facts := ExtractMSBuild(file("lib/Corpus.csproj", `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFrameworks>net8.0;net472</TargetFrameworks></PropertyGroup>
</Project>
`))
	facts.Normalize()
	if facts.Module.LangVersion != "net8.0;net472" {
		t.Errorf("frameworks = %q, want both", facts.Module.LangVersion)
	}
}

// An ill-formed csproj still declares readable dependencies up to the point it breaks, and
// a hand-edited one is the normal way that happens.
func TestMSBuildMalformedKeepsWhatItRead(t *testing.T) {
	facts := ExtractMSBuild(file("a.csproj", `<Project>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>
`))
	if !facts.Incomplete {
		t.Error("an unterminated project must be marked incomplete")
	}
	facts.Normalize()
	depOf(t, facts, "Serilog", ScopeRuntime)
}

func TestSolutionExtraction(t *testing.T) {
	facts := ExtractSolution(file("Ordering.sln", `
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Ordering.Api", "src\Ordering.Api\Ordering.Api.csproj", "{A1}"
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Ordering.Domain", "src\Ordering.Domain\Ordering.Domain.csproj", "{A2}"
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{A3}"
Global
EndGlobal
`))
	facts.Normalize()

	if facts.Module.Name != "Ordering" {
		t.Errorf("solution name = %q", facts.Module.Name)
	}
	// A solution is the only file in a .NET repository naming every project at once, which
	// is a workspace declaration in the same sense npm's `workspaces` is.
	want := "src/Ordering.Api/Ordering.Api.csproj,src/Ordering.Domain/Ordering.Domain.csproj"
	if got := strings.Join(facts.Module.Workspaces, ","); got != want {
		t.Errorf("workspaces = %q, want %q", got, want)
	}
	// A solution folder groups projects in the IDE and is not one. Recording it would put
	// a workspace member at a path that holds no project.
	for _, w := range facts.Module.Workspaces {
		if w == "src" {
			t.Error("a solution folder was recorded as a project")
		}
	}
	// A solution declares no dependencies at all, which is why it is its own Kind: folded
	// into KindMSBuild it would read as a NuGet manifest declaring nothing.
	if len(facts.Deps) != 0 {
		t.Errorf("deps = %v, want none", facts.DepNames())
	}
}
