package manifest

import (
	"encoding/xml"
	"io"
	"path"
	"strings"

	"github.com/3rg0n/signpost/internal/discover"
)

// ExtractMSBuild reads a .csproj, .fsproj, .vbproj, or one of MSBuild's two shared
// property files.
//
// Parsed with encoding/xml's token stream rather than by line, which is the one place this
// package reaches for a real parser and is worth saying why: an MSBuild element carries its
// facts in attributes, `<PackageReference Include="Serilog" Version="4.0.0" />` and the same
// reference with `<Version>4.0.0</Version>` as a child element mean the same thing, and both
// spellings are generated by different versions of the tooling. A line reader would have to
// reconstruct attribute quoting and element nesting to tell them apart, which is what an XML
// decoder already does. Line numbers survive through Decoder.InputPos, so provenance still
// points at the declaration.
//
// Three fact kinds come out of it, and the middle one is what makes this reader worth having
// for a .NET repository specifically:
//
//   - PackageReference is a NuGet dependency. PackageVersion is the same dependency's version
//     declared centrally in Directory.Packages.props, which is where a modern solution keeps
//     every version — so a repository using Central Package Management states its whole
//     supply chain in one file that a csproj-only reader would find nothing in.
//   - **ProjectReference is an edge between two projects in this repository**, and it is
//     stated nowhere else. C# has no manifest naming its own modules and no import that
//     crosses a project boundary visibly: `using Ordering.Domain` looks identical whether
//     Ordering.Domain is a project in the tree or a package from nuget.org. The
//     ProjectReference is what distinguishes them, so it is recorded as a Local dependency —
//     the same shape a Terraform local module source takes, and for the same reason: the
//     declaration becomes an edge onto the module holding that code rather than a reference
//     page claiming the repository pulls its own project in from outside.
//   - The target framework, which is .NET's toolchain floor.
func ExtractMSBuild(f discover.File) Facts {
	facts := Facts{Path: f.Path, Class: f.Class, Kind: KindMSBuild}
	dir := dirOfPath(f.Path)
	facts.Module = Module{
		// The project's identity is its filename unless it says otherwise, which is
		// MSBuild's own rule: AssemblyName defaults to the project file's base name, and
		// almost no project overrides it.
		Name:      strings.TrimSuffix(path.Base(f.Path), path.Ext(f.Path)),
		Ecosystem: "nuget",
		Line:      1,
	}

	dec := xml.NewDecoder(strings.NewReader(f.Content))
	// A csproj is XML but is not always *valid* XML to a strict decoder: a hand-edited file
	// may carry a stray entity, and an ill-formed one still declares readable dependencies
	// up to the point it breaks. Strict off keeps those; a genuine structural error still
	// ends the walk below and is reported as incomplete.
	dec.Strict = false

	// A pending reference, held while its children are read: the child-element spelling of
	// Version arrives after the start tag that named the package.
	var pending *Dep
	var elem string

	for {
		tok, err := dec.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			facts.markIncomplete("MSBuild project did not fully parse: " + err.Error())
			break
		}
		line, _ := dec.InputPos()

		switch t := tok.(type) {
		case xml.StartElement:
			elem = t.Name.Local
			switch elem {
			case "PackageReference", "PackageVersion", "GlobalPackageReference":
				// Include names a new reference; Update sets properties on one declared
				// elsewhere, which is how Directory.Build.props adjusts a version without
				// declaring the dependency again. Both name the same package, and the dedupe
				// in Normalize folds the pair.
				name := firstAttr(t, "Include", "Update")
				if name == "" {
					break
				}
				d := Dep{
					Name: name, Ecosystem: "nuget", Line: line,
					Version: firstAttr(t, "Version", "VersionOverride"),
					Scope:   msbuildScope(t),
				}
				pending = &d

			case "ProjectReference":
				inc := firstAttr(t, "Include")
				if inc == "" {
					break
				}
				// The path is written with backslashes — `..\Ordering.Domain\Ordering.Domain.csproj`
				// — because MSBuild is a Windows-first tool, and every path signpost records is
				// slash-separated on every platform.
				target := joinRepoPath(dir, strings.ReplaceAll(inc, `\`, "/"))
				d := Dep{
					// Named for the project rather than for the path, so the name matches the
					// namespace a `using` would name and reads as a project rather than a file.
					Name:      strings.TrimSuffix(path.Base(target), path.Ext(target)),
					Ecosystem: "nuget", Scope: ScopeRuntime, Line: line,
					Source: dirOfPath(target), Local: true,
				}
				facts.Deps = append(facts.Deps, d)
			}

		case xml.CharData:
			text := strings.TrimSpace(string(t))
			if text == "" {
				break
			}
			switch elem {
			case "Version", "VersionOverride":
				// The child-element spelling, which only means anything inside a reference.
				if pending != nil && pending.Version == "" {
					pending.Version = text
				}
			case "TargetFramework", "TargetFrameworks":
				// `net8.0;net472` is a project that builds for both. Kept whole: which
				// frameworks a project targets is one fact, and the first alone would hide
				// that it is multi-targeted.
				facts.Module.LangVersion = text
			case "AssemblyName", "RootNamespace":
				// RootNamespace is the namespace the project's files declare, which is what a
				// `using` in another project names — the more useful identity of the two, and
				// the reason it is allowed to win.
				if elem == "RootNamespace" || facts.Module.Name == "" {
					facts.Module.Name = text
				}
			case "OutputType":
				// `Exe` and `WinExe` are the two that produce something runnable. A `Library`
				// is not an entrypoint, and recording one would put every class library in the
				// list of things you can start.
				if strings.EqualFold(text, "Exe") || strings.EqualFold(text, "WinExe") {
					facts.Entrypoints = append(facts.Entrypoints, Entrypoint{
						Name: facts.Module.Name, Path: f.Path, Line: line,
					})
				}
			}

		case xml.EndElement:
			switch t.Name.Local {
			case "PackageReference", "PackageVersion", "GlobalPackageReference":
				if pending != nil {
					facts.Deps = append(facts.Deps, *pending)
					pending = nil
				}
			}
			elem = ""
		}
	}
	// A self-closing `<PackageReference ... />` produces a StartElement and an EndElement, so
	// the loop above already flushed it. This covers the truncated file, where the closing tag
	// never arrived and the dependency is still a real declaration.
	if pending != nil {
		facts.Deps = append(facts.Deps, *pending)
	}
	return facts
}

// msbuildScope reads the scope a PackageReference declares.
//
// `PrivateAssets="all"` is the marker, and it maps to ScopeBuild rather than ScopeDev
// because of what it actually says: the package is used to build this project and is *not*
// propagated to anything that consumes it. That is the same claim npm's peerDependencies
// make from the other side, which npmScopes already maps to ScopeBuild. An analyzer or a
// source generator is the usual case, and calling it a runtime dependency would overstate
// what the built assembly needs.
func msbuildScope(t xml.StartElement) DepScope {
	for _, a := range t.Attr {
		if a.Name.Local == "PrivateAssets" && strings.Contains(strings.ToLower(a.Value), "all") {
			return ScopeBuild
		}
	}
	return ScopeRuntime
}

// firstAttr returns the first of the named attributes the element carries, matched
// case-insensitively because MSBuild treats attribute names that way.
func firstAttr(t xml.StartElement, names ...string) string {
	for _, want := range names {
		for _, a := range t.Attr {
			if strings.EqualFold(a.Name.Local, want) {
				if v := strings.TrimSpace(a.Value); v != "" {
					return v
				}
			}
		}
	}
	return ""
}

// ExtractSolution reads a Visual Studio .sln for the projects it contains.
//
// A solution declares no dependencies — only membership — which is why it is its own Kind:
// folded into KindMSBuild it would read as a NuGet manifest declaring nothing, and "this
// project has no dependencies" is a different statement from "this file never listed any".
//
// What it does declare is which projects make up the repository, and that is a workspace
// declaration in exactly the sense npm's `workspaces` and Cargo's `members` are. Worth
// reading for that alone: a solution is the only file in a .NET repository that names every
// project at once, and the count is the answer to "how many things are in here".
//
// Line-oriented rather than parsed, because a .sln is not XML — it is a line format with a
// GUID grammar, and the one line that matters has a fixed shape:
//
//	Project("{FAE04EC0-...}") = "Ordering.Api", "src\Ordering.Api\Ordering.Api.csproj", "{...}"
func ExtractSolution(f discover.File) Facts {
	facts := Facts{Path: f.Path, Class: f.Class, Kind: KindSolution}
	facts.Module = Module{
		Name:      strings.TrimSuffix(path.Base(f.Path), path.Ext(f.Path)),
		Ecosystem: "nuget",
		Line:      1,
	}
	dir := dirOfPath(f.Path)

	for _, raw := range strings.Split(strings.ReplaceAll(f.Content, "\r\n", "\n"), "\n") {
		line := strings.TrimSpace(raw)
		if !strings.HasPrefix(line, `Project("{`) {
			continue
		}
		_, rest, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		fields := splitSolutionFields(rest)
		if len(fields) < 2 {
			continue
		}
		p := strings.ReplaceAll(fields[1], `\`, "/")
		// A solution folder is a Project entry whose "path" is just the folder's name, with
		// no extension — it groups projects in the IDE and is not one. Recording it would put
		// a workspace member at a directory that does not exist.
		if path.Ext(p) == "" {
			continue
		}
		facts.Module.Workspaces = append(facts.Module.Workspaces, joinRepoPath(dir, p))
	}
	return facts
}

// splitSolutionFields returns the quoted fields of a .sln Project line, in order.
func splitSolutionFields(s string) []string {
	var out []string
	for {
		i := strings.IndexByte(s, '"')
		if i < 0 {
			return out
		}
		s = s[i+1:]
		j := strings.IndexByte(s, '"')
		if j < 0 {
			return out
		}
		out = append(out, strings.TrimSpace(s[:j]))
		s = s[j+1:]
	}
}
